# Generated by Django 6.0.4 on 2026-05-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(blank=True, max_length=128, null=True)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('phone', models.CharField(max_length=32)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
