# Generated by Django 6.0.4 on 2026-05-27 00:00
# This migration now creates the missing POS tables for normal relational databases.
# The original no-op migration caused project state and fresh-database migration failures.

from decimal import Decimal
import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_adminuser_appsettings_admintoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128, blank=True)),
                ('status', models.CharField(choices=[('available', '🟢 Available'), ('occupied', '🔴 Occupied'), ('cleaning', '🧹 Cleaning'), ('reserved', '🟡 Reserved')], default='available', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=payments.models.generate_uuid_hex, editable=False, max_length=64, unique=True)),
                ('phone', models.CharField(max_length=32, blank=True)),
                ('status', models.CharField(default='pending', db_index=True, max_length=32)),
                ('split_count', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='orders', to='payments.table')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('modifiers', models.JSONField(blank=True, null=True, default=list)),
                ('seat_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=models.CASCADE, related_name='items', to='payments.order')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='transactions', to='payments.order'),
        ),
    ]
