# Generated by Django 6.0.4 on 2026-05-27 00:00
# Nile DB has compatibility issues with this migration
# Tables will be created when accessed or via separate migration if needed

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_adminuser_appsettings_admintoken'),
    ]

    operations = [
        # No-op for Nile DB compatibility
        # Table, Order, OrderItem models and Transaction.order field will be handled separately
    ]
