# Generated by Django 6.0.4 on 2026-05-27 12:10
# MODIFIED: Removed Order.order_id alteration since Order table skipped in 0003

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_pos_tables_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintoken',
            name='token',
            field=models.CharField(default=payments.models.generate_uuid_hex, editable=False, max_length=64, unique=True),
        ),
        # Order.order_id alteration skipped - Order table not created in 0003
    ]
