# Generated by Django 6.0.4 on 2026-05-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_wastagelog_orderitem_food_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash')], default='mpesa', max_length=32),
        ),
    ]
