# Generated by Django 6.0.4 on 2026-05-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='failed_login_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
