# Generated by Django 6.0.4 on 2026-05-30 16:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='min_stock_level',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='stock_level',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='payments.menuitem')),
            ],
        ),
    ]
