# Generated by Django 6.0.4 on 2026-05-30 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_menuitem_min_stock_level_menuitem_stock_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='payments.adminuser')),
            ],
        ),
        migrations.AddField(
            model_name='admintoken',
            name='session_log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.adminsessionlog'),
        ),
    ]
