# Generated by Django 6.0.4 on 2026-05-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_adminsessionlog_admintoken_session_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
