# Generated by GitHub Copilot

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_delivery_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(default=0, decimal_places=2, max_digits=10),
        ),
    ]
