# Generated by Django 5.0.6 on 2024-06-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_order_delivery_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]