# Generated by Django 6.0.6 on 2026-06-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_served',
            field=models.BooleanField(default=False),
        ),
    ]
