# Generated by Django 6.0.6 on 2026-06-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_orderitem_is_served'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='waiter_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(default='table', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='unpaid', max_length=32),
        ),
    ]
