# Generated by Django 6.0.3 on 2026-06-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_order_waiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='employee',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='employee-documents/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='special_id',
            field=models.CharField(blank=True, default='', help_text='Special waiter ID number', max_length=50),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='Optional stock-keeping unit', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('bill_pending', 'Bill Pending'), ('ready', 'Ready'), ('paid', 'Paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32),
        ),
    ]
