# Generated by Django 6.0.3 on 2026-06-29 13:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0028_add_mpesa_receipt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='miscellaneousexpense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='staffactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wastagelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['-created_at'], name='employee_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status', '-created_at'], name='employee_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['role'], name='employee_role_idx'),
        ),
        migrations.AddIndex(
            model_name='miscellaneousexpense',
            index=models.Index(fields=['-created_at'], name='miscexp_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='order_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['waiter_id', '-created_at'], name='order_waiter_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='order_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'waiter_id'], name='order_status_waiter_idx'),
        ),
        migrations.AddIndex(
            model_name='staffactivity',
            index=models.Index(fields=['-created_at'], name='staffact_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='staffactivity',
            index=models.Index(fields=['employee_id', '-created_at'], name='staffact_emp_created_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklog',
            index=models.Index(fields=['-created_at'], name='stocklog_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='wastagelog',
            index=models.Index(fields=['-created_at'], name='wastage_created_desc_idx'),
        ),
    ]
