# Generated by Django 6.0.3 on 2026-07-02 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0029_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_orders', to='payments.employee'),
        ),
        migrations.AddField(
            model_name='order',
            name='claimed_by_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
