# Generated by Django 6.0.4 on 2026-05-27 12:10

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_pos_tables_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintoken',
            name='token',
            field=models.CharField(default=payments.models.generate_uuid_hex, editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=payments.models.generate_uuid_hex, editable=False, max_length=64, unique=True),
        ),
    ]
