# Generated by GitHub Copilot

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_employee_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='delivery_rate_per_km',
            field=models.DecimalField(default=100, max_digits=10, decimal_places=2),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='min_delivery_fee',
            field=models.DecimalField(default=50, max_digits=10, decimal_places=2),
        ),
    ]
