# Generated by Django 6.0.3 on 2026-06-08 16:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_order_delivery_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscellaneousExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('reason', models.CharField(blank=True, max_length=512)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
