"""
Django settings for tastybites project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the backend .env file if it exists.
env_candidates = [BASE_DIR / '.env', BASE_DIR.parent / '.env', BASE_DIR.parent.parent / '.env']
for env_path in env_candidates:
    if env_path.exists():
        load_dotenv(env_path, override=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-_@p9bh$hzz=4m+xdxf^%xq*b=-fzly00i+priz4tl$we#3y*q%')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Allow local/dev hosts by default; override via env var if needed
DEFAULT_ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '[::1]',
    '.vercel.app',
    '.onrender.com',
    '.loca.lt',
    '.ngrok-free.app',
    '.ngrok.io',
]
ALLOWED_HOSTS = os.environ.get(
    'ALLOWED_HOSTS',
    ','.join(DEFAULT_ALLOWED_HOSTS)
).replace(' ', '').replace(';', ',').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'payments',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tastybites.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tastybites.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

raw_db_url = os.environ.get('DATABASE_URL', '') or None
if not raw_db_url:
    raw_db_url = os.environ.get('tastybites_POSTGRES_URL', '') or None
if not raw_db_url:
    raw_db_url = os.environ.get('tastybites_NILEDB_URL', '') or None
if not raw_db_url:
    raw_db_url = os.environ.get('tastybites_NILEDB_POSTGRES_URL', '') or None
if isinstance(raw_db_url, str):
    raw_db_url = raw_db_url.strip()
    placeholder_markers = ('[YOUR-PASSWORD]', '<your', 'your-password', 'your-db-url', 'YOUR-PASSWORD', 'postgresql://postgres:', 'postgres://postgres:')
    if not raw_db_url or any(marker in raw_db_url for marker in placeholder_markers) or ('[' in raw_db_url and ']' in raw_db_url):
        raw_db_url = None

if raw_db_url:
    DATABASES = {
        'default': dj_database_url.parse(raw_db_url, conn_max_age=600)
    }
else:
    DATABASES = {
        'default': dj_database_url.config(
            default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
            conn_max_age=600
        )
    }
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.environ.get('DJANGO_MEDIA_ROOT', BASE_DIR / 'media'))
try:
    MEDIA_ROOT.mkdir(parents=True, exist_ok=True)
except OSError:
    MEDIA_ROOT = Path(os.environ.get('TMPDIR', os.environ.get('TMP', '/tmp'))) / 'media'
    MEDIA_ROOT.mkdir(parents=True, exist_ok=True)
else:
    if not os.access(str(MEDIA_ROOT), os.W_OK):
        MEDIA_ROOT = Path(os.environ.get('TMPDIR', os.environ.get('TMP', '/tmp'))) / 'media'
        MEDIA_ROOT.mkdir(parents=True, exist_ok=True)

# M-Pesa Daraja API Config
MPESA_ENVIRONMENT = os.environ.get('MPESA_ENVIRONMENT', 'sandbox')

MPESA_CONSUMER_KEY = os.environ.get('MPESA_CONSUMER_KEY', 'kwCn9sG1ySJ6NWcHduKaXOAnNu6DkbwI9v096WTmsHG8XMVq')
MPESA_CONSUMER_SECRET = os.environ.get('MPESA_CONSUMER_SECRET', '6PcwyDSoN8R4V4VxVUAP9uGCGYi9Cm67xDRUtiUCA0RzXvXIE8FtCEc1zYPOnZXu')

MPESA_SHORTCODE = '174379'
MPESA_EXPRESS_SHORTCODE = '174379'
MPESA_PASSKEY = 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
MPESA_INITIATOR_USERNAME = 'Tasty Bites'
# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'False') == 'True'

# Allow frontend domain from environment
if not CORS_ALLOW_ALL_ORIGINS:
    frontend_url = os.environ.get('CORS_ALLOWED_ORIGINS', '')
    # Ensure we handle multiple origins, trim whitespace, and remove trailing slashes
    CORS_ALLOWED_ORIGINS = [url.strip().rstrip('/') for url in frontend_url.split(',') if url.strip()] 
    if not CORS_ALLOWED_ORIGINS:
        # Default to localhost:5173 and 5174 for development (Vite default and fallback ports)
        CORS_ALLOWED_ORIGINS = ['http://localhost:5173', 'http://127.0.0.1:5173', 'http://localhost:5174', 'http://127.0.0.1:5174']

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + ['Authorization', 'X-ADMIN-TOKEN', 'X-STAFF-TOKEN']
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# CSRF Trusted Origins for production
DEFAULT_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:5174',
    'http://127.0.0.1:5174',
    'https://tastybites-hub-local.loca.lt',
]
CSRF_TRUSTED_ORIGINS = os.environ.get(
    'CSRF_TRUSTED_ORIGINS',
    ','.join(DEFAULT_TRUSTED_ORIGINS)
).replace(' ', '').replace(';', ',').split(',')
# MPESA callback URL can be overridden via environment variable.


# Default to the local server callback endpoint so local testing works without ngrok/webhook.site.
MPESA_CALLBACK_URL = os.environ.get(
    'MPESA_CALLBACK_URL',
    # IMPORTANT: Safaricom requires a public HTTPS callback.
    # For local/dev without ngrok/webhook, set MPESA_CALLBACK_URL to a reachable HTTPS URL.
    # Leaving it blank will allow the request-based callback URL builder to construct the correct hosted URL.
    ''
)





# Optional: default/test phone to prefill the frontend when initiating STK
MPESA_TEST_PHONE = os.environ.get('MPESA_TEST_PHONE', '')
MPESA_ADMIN_TOKEN = os.environ.get('MPESA_ADMIN_TOKEN', 'dev-admin-token')

# Email Configuration for sending employee emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'omollogeorge096@gmail.com') # Your Gmail address
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'xqyeohuglxczgqze')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', f"Tasty Bites Admin <{EMAIL_HOST_USER}>")

MPESA_TO_KES_RATE = float(os.environ.get('MPESA_TO_KES_RATE', '1'))

# Production Security Settings
if not DEBUG:
    # Only redirect to HTTPS if we are not on localhost/127.0.0.1
    # This prevents ERR_SSL_PROTOCOL_ERROR during local testing with DEBUG=False
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True') == 'True'
    
    # Trust the X-Forwarded-Proto header from the hosting proxy
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_SECURITY_POLICY = {
        'default-src': ("'self'", "https:"),
        'img-src': ("'self'", "data:", "https:"),
        'connect-src': ("'self'", "https:"),
    }